# Startup Production Environment Configuration
# Use case: Production Databricks + EMR for large-scale data processing
# Higher budgets, more selective AI analysis

project:
  name: aws-alert-intelligence
  environment: startup-prod
  version: 2.0.0

# Budget configuration - Startup production scale
budgets:
  daily_limit: 100.00     # $100/day for production workloads
  monthly_limit: 3000.00  # $3000/month production budget
  monthly_threshold_warning: 80   # Alert at 80% ($2400)
  monthly_threshold_critical: 100 # Alert at 100% ($3000)
  currency: USD
  time_unit_monthly: MONTHLY
  time_unit_daily: DAILY

aws:
  region: us-east-1
  account_id: "987654321098"  # Production AWS account
  stack_prefix: AlertIntelProd

dashboard:
  enabled: true
  name: ProductionCostMonitoring
  top_services_count: 15  # More detailed dashboard
  auto_refresh_seconds: 180  # Faster refresh for production
  metric_period_seconds: 3600  # Hourly metrics

notifications:
  email_enabled: true  # Email + Slack for production
  slack_enabled: true
  critical_topic_name: production-critical-alerts
  heartbeat_topic_name: production-heartbeat
  routing:
    daily_budget_exceeded: heartbeat  # Daily overruns are warnings in prod
    monthly_warning: critical  # 80% monthly is critical for production
    monthly_exceeded: critical

# AI analysis - More selective for cost optimization
ai_analysis:
  enabled: true
  rules:
    analyze_budget_warning: true
    analyze_budget_critical: true
    analyze_daily_budget_exceeded: false  # Don't analyze daily in production
    analyze_daily_budget_report: false
    analyze_cloudwatch_alarm_error: true
    analyze_cloudwatch_alarm_warning: false  # Only errors in production
    analyze_cloudwatch_alarm_info: false
    analyze_emr_cluster_failure: true
    analyze_emr_step_failure: true
    analyze_emr_bootstrap_failure: true
    analyze_custom_error_events: true
    analyze_custom_warning_events: false
  blacklist:
    - "HealthCheckSuccess"
    - "MaintenanceWindowStarted"
    - "ScheduledScalingEvent"  # Don't analyze routine scaling
    - "AutoScalingGroupUpdate"
  whitelist:
    - "ProductionFailure"
    - "DataLoss"
    - "CustomerImpact"
    - "EMR.*TERMINATED_WITH_ERRORS"

# EMR monitoring - Production data pipeline
emr:
  enabled: true
  monitored_clusters:
    - "prod-.*"  # Only production clusters
    - "data-pipeline-.*"
  routing:
    cluster_failure: critical
    step_failure: critical
    bootstrap_failure: critical
    cluster_terminated: heartbeat
    cluster_started: heartbeat
  tools:
    max_failed_steps: 20  # More context for production
    max_log_lines: 100
    include_spark_logs: true

# Databricks configuration (future integration)
databricks:
  enabled: false  # Not yet implemented
  # workspace_url: https://...
  # monitoring_enabled: true

daily_report:
  enabled: true
  schedule_hour_utc: 13  # 1pm UTC = 8am EST = 5am PST

chatbot:
  read_only_access: true
  logging_level: ERROR  # Less verbose in production
  user_role_required: true  # Require role assumption in production

tags:
  Project: AWS Alert Intelligence
  ManagedBy: CDK
  Environment: production
  CostCenter: Engineering
  Owner: DevOps Team
  Compliance: SOC2
